fragment ConcertParts on Concert {
  __typename
  title
  date
  locale
  translationKey
  program
  description
  image
  helloAssoLink
  mapsLink
  mapsLabel
  ticketLabel
}

fragment MusicianParts on Musician {
  __typename
  name
  locale
  translationKey
  instrument
  photo
  photoCredit
  bio
}

fragment FestivalParts on Festival {
  __typename
  title
  locale
  translationKey
  subtitle
  image
  imageCaption
  body
}

fragment HomepageParts on Homepage {
  __typename
  title
  locale
  translationKey
  heroTitle
  heroSubtitle
  introTitle
  introDescription
  nextConcertCtaLabel
}

fragment TicketInfoParts on TicketInfo {
  __typename
  title
  locale
  translationKey
  sectionTitle
  sectionSubtitle
  discountText
  email
  cards {
    __typename
    title
    text
  }
}

fragment ContactInfoParts on ContactInfo {
  __typename
  title
  locale
  translationKey
  email
  address
  phone
  mapEmbedUrl
  facebookUrl
  instagramUrl
}

fragment SupportInfoParts on SupportInfo {
  __typename
  title
  locale
  translationKey
  subtitle
  membershipUrl
  donationUrl
  membershipTitle
  membershipText
  donationTitle
  donationText
}
