//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  concert: Concert;
  concertConnection: ConcertConnection;
  musician: Musician;
  musicianConnection: MusicianConnection;
  festival: Festival;
  festivalConnection: FestivalConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  ticketInfo: TicketInfo;
  ticketInfoConnection: TicketInfoConnection;
  contactInfo: ContactInfo;
  contactInfoConnection: ContactInfoConnection;
  supportInfo: SupportInfo;
  supportInfoConnection: SupportInfoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConcertArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConcertConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConcertFilter>;
};


export type QueryMusicianArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMusicianConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MusicianFilter>;
};


export type QueryFestivalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFestivalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FestivalFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryTicketInfoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTicketInfoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TicketInfoFilter>;
};


export type QueryContactInfoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactInfoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactInfoFilter>;
};


export type QuerySupportInfoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySupportInfoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SupportInfoFilter>;
};

export type DocumentFilter = {
  concert?: InputMaybe<ConcertFilter>;
  musician?: InputMaybe<MusicianFilter>;
  festival?: InputMaybe<FestivalFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  ticketInfo?: InputMaybe<TicketInfoFilter>;
  contactInfo?: InputMaybe<ContactInfoFilter>;
  supportInfo?: InputMaybe<SupportInfoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Concert | Musician | Festival | Homepage | TicketInfo | ContactInfo | SupportInfo | Folder;

export type Concert = Node & Document & {
  __typename?: 'Concert';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  program: Scalars['JSON']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  helloAssoLink?: Maybe<Scalars['String']['output']>;
  mapsLink?: Maybe<Scalars['String']['output']>;
  mapsLabel?: Maybe<Scalars['String']['output']>;
  ticketLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConcertFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  program?: InputMaybe<RichTextFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  helloAssoLink?: InputMaybe<StringFilter>;
  mapsLink?: InputMaybe<StringFilter>;
  mapsLabel?: InputMaybe<StringFilter>;
  ticketLabel?: InputMaybe<StringFilter>;
};

export type ConcertConnectionEdges = {
  __typename?: 'ConcertConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Concert>;
};

export type ConcertConnection = Connection & {
  __typename?: 'ConcertConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConcertConnectionEdges>>>;
};

export type Musician = Node & Document & {
  __typename?: 'Musician';
  name: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  instrument: Scalars['String']['output'];
  photo: Scalars['String']['output'];
  photoCredit?: Maybe<Scalars['String']['output']>;
  bio: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MusicianFilter = {
  name?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  instrument?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  photoCredit?: InputMaybe<StringFilter>;
  bio?: InputMaybe<RichTextFilter>;
};

export type MusicianConnectionEdges = {
  __typename?: 'MusicianConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Musician>;
};

export type MusicianConnection = Connection & {
  __typename?: 'MusicianConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MusicianConnectionEdges>>>;
};

export type Festival = Node & Document & {
  __typename?: 'Festival';
  title: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageCaption?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FestivalFilter = {
  title?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageCaption?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FestivalConnectionEdges = {
  __typename?: 'FestivalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Festival>;
};

export type FestivalConnection = Connection & {
  __typename?: 'FestivalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FestivalConnectionEdges>>>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  title: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  heroTitle: Scalars['String']['output'];
  heroSubtitle: Scalars['String']['output'];
  introTitle?: Maybe<Scalars['String']['output']>;
  introDescription?: Maybe<Scalars['String']['output']>;
  nextConcertCtaLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageFilter = {
  title?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  introTitle?: InputMaybe<StringFilter>;
  introDescription?: InputMaybe<StringFilter>;
  nextConcertCtaLabel?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type TicketInfoCards = {
  __typename?: 'TicketInfoCards';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type TicketInfo = Node & Document & {
  __typename?: 'TicketInfo';
  title: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  sectionTitle?: Maybe<Scalars['String']['output']>;
  sectionSubtitle?: Maybe<Scalars['String']['output']>;
  discountText?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<TicketInfoCards>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TicketInfoCardsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type TicketInfoFilter = {
  title?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  sectionTitle?: InputMaybe<StringFilter>;
  sectionSubtitle?: InputMaybe<StringFilter>;
  discountText?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  cards?: InputMaybe<TicketInfoCardsFilter>;
};

export type TicketInfoConnectionEdges = {
  __typename?: 'TicketInfoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TicketInfo>;
};

export type TicketInfoConnection = Connection & {
  __typename?: 'TicketInfoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TicketInfoConnectionEdges>>>;
};

export type ContactInfo = Node & Document & {
  __typename?: 'ContactInfo';
  title: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  email?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  mapEmbedUrl?: Maybe<Scalars['String']['output']>;
  facebookUrl?: Maybe<Scalars['String']['output']>;
  instagramUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactInfoFilter = {
  title?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  mapEmbedUrl?: InputMaybe<StringFilter>;
  facebookUrl?: InputMaybe<StringFilter>;
  instagramUrl?: InputMaybe<StringFilter>;
};

export type ContactInfoConnectionEdges = {
  __typename?: 'ContactInfoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ContactInfo>;
};

export type ContactInfoConnection = Connection & {
  __typename?: 'ContactInfoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactInfoConnectionEdges>>>;
};

export type SupportInfo = Node & Document & {
  __typename?: 'SupportInfo';
  title: Scalars['String']['output'];
  locale: Scalars['String']['output'];
  translationKey: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  membershipUrl?: Maybe<Scalars['String']['output']>;
  donationUrl?: Maybe<Scalars['String']['output']>;
  membershipTitle?: Maybe<Scalars['String']['output']>;
  membershipText?: Maybe<Scalars['String']['output']>;
  donationTitle?: Maybe<Scalars['String']['output']>;
  donationText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SupportInfoFilter = {
  title?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  translationKey?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  membershipUrl?: InputMaybe<StringFilter>;
  donationUrl?: InputMaybe<StringFilter>;
  membershipTitle?: InputMaybe<StringFilter>;
  membershipText?: InputMaybe<StringFilter>;
  donationTitle?: InputMaybe<StringFilter>;
  donationText?: InputMaybe<StringFilter>;
};

export type SupportInfoConnectionEdges = {
  __typename?: 'SupportInfoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SupportInfo>;
};

export type SupportInfoConnection = Connection & {
  __typename?: 'SupportInfoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SupportInfoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateConcert: Concert;
  createConcert: Concert;
  updateMusician: Musician;
  createMusician: Musician;
  updateFestival: Festival;
  createFestival: Festival;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateTicketInfo: TicketInfo;
  createTicketInfo: TicketInfo;
  updateContactInfo: ContactInfo;
  createContactInfo: ContactInfo;
  updateSupportInfo: SupportInfo;
  createSupportInfo: SupportInfo;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateConcertArgs = {
  relativePath: Scalars['String']['input'];
  params: ConcertMutation;
};


export type MutationCreateConcertArgs = {
  relativePath: Scalars['String']['input'];
  params: ConcertMutation;
};


export type MutationUpdateMusicianArgs = {
  relativePath: Scalars['String']['input'];
  params: MusicianMutation;
};


export type MutationCreateMusicianArgs = {
  relativePath: Scalars['String']['input'];
  params: MusicianMutation;
};


export type MutationUpdateFestivalArgs = {
  relativePath: Scalars['String']['input'];
  params: FestivalMutation;
};


export type MutationCreateFestivalArgs = {
  relativePath: Scalars['String']['input'];
  params: FestivalMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateTicketInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: TicketInfoMutation;
};


export type MutationCreateTicketInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: TicketInfoMutation;
};


export type MutationUpdateContactInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactInfoMutation;
};


export type MutationCreateContactInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactInfoMutation;
};


export type MutationUpdateSupportInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: SupportInfoMutation;
};


export type MutationCreateSupportInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: SupportInfoMutation;
};

export type DocumentUpdateMutation = {
  concert?: InputMaybe<ConcertMutation>;
  musician?: InputMaybe<MusicianMutation>;
  festival?: InputMaybe<FestivalMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  ticketInfo?: InputMaybe<TicketInfoMutation>;
  contactInfo?: InputMaybe<ContactInfoMutation>;
  supportInfo?: InputMaybe<SupportInfoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  concert?: InputMaybe<ConcertMutation>;
  musician?: InputMaybe<MusicianMutation>;
  festival?: InputMaybe<FestivalMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  ticketInfo?: InputMaybe<TicketInfoMutation>;
  contactInfo?: InputMaybe<ContactInfoMutation>;
  supportInfo?: InputMaybe<SupportInfoMutation>;
};

export type ConcertMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  program?: InputMaybe<Scalars['JSON']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  helloAssoLink?: InputMaybe<Scalars['String']['input']>;
  mapsLink?: InputMaybe<Scalars['String']['input']>;
  mapsLabel?: InputMaybe<Scalars['String']['input']>;
  ticketLabel?: InputMaybe<Scalars['String']['input']>;
};

export type MusicianMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  instrument?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  photoCredit?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['JSON']['input']>;
};

export type FestivalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageCaption?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomepageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  introTitle?: InputMaybe<Scalars['String']['input']>;
  introDescription?: InputMaybe<Scalars['String']['input']>;
  nextConcertCtaLabel?: InputMaybe<Scalars['String']['input']>;
};

export type TicketInfoCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type TicketInfoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  sectionSubtitle?: InputMaybe<Scalars['String']['input']>;
  discountText?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<TicketInfoCardsMutation>>>;
};

export type ContactInfoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  mapEmbedUrl?: InputMaybe<Scalars['String']['input']>;
  facebookUrl?: InputMaybe<Scalars['String']['input']>;
  instagramUrl?: InputMaybe<Scalars['String']['input']>;
};

export type SupportInfoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  locale?: InputMaybe<Scalars['String']['input']>;
  translationKey?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  membershipUrl?: InputMaybe<Scalars['String']['input']>;
  donationUrl?: InputMaybe<Scalars['String']['input']>;
  membershipTitle?: InputMaybe<Scalars['String']['input']>;
  membershipText?: InputMaybe<Scalars['String']['input']>;
  donationTitle?: InputMaybe<Scalars['String']['input']>;
  donationText?: InputMaybe<Scalars['String']['input']>;
};

export type ConcertPartsFragment = { __typename: 'Concert', title: string, date: string, locale: string, translationKey: string, program: any, description?: string | null, image?: string | null, helloAssoLink?: string | null, mapsLink?: string | null, mapsLabel?: string | null, ticketLabel?: string | null };

export type MusicianPartsFragment = { __typename: 'Musician', name: string, locale: string, translationKey: string, instrument: string, photo: string, photoCredit?: string | null, bio: any };

export type FestivalPartsFragment = { __typename: 'Festival', title: string, locale: string, translationKey: string, subtitle?: string | null, image?: string | null, imageCaption?: string | null, body: any };

export type HomepagePartsFragment = { __typename: 'Homepage', title: string, locale: string, translationKey: string, heroTitle: string, heroSubtitle: string, introTitle?: string | null, introDescription?: string | null, nextConcertCtaLabel?: string | null };

export type TicketInfoPartsFragment = { __typename: 'TicketInfo', title: string, locale: string, translationKey: string, sectionTitle?: string | null, sectionSubtitle?: string | null, discountText?: string | null, email?: string | null, cards?: Array<{ __typename: 'TicketInfoCards', title?: string | null, text?: string | null } | null> | null };

export type ContactInfoPartsFragment = { __typename: 'ContactInfo', title: string, locale: string, translationKey: string, email?: string | null, address?: string | null, phone?: string | null, mapEmbedUrl?: string | null, facebookUrl?: string | null, instagramUrl?: string | null };

export type SupportInfoPartsFragment = { __typename: 'SupportInfo', title: string, locale: string, translationKey: string, subtitle?: string | null, membershipUrl?: string | null, donationUrl?: string | null, membershipTitle?: string | null, membershipText?: string | null, donationTitle?: string | null, donationText?: string | null };

export type ConcertQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConcertQuery = { __typename?: 'Query', concert: { __typename: 'Concert', id: string, title: string, date: string, locale: string, translationKey: string, program: any, description?: string | null, image?: string | null, helloAssoLink?: string | null, mapsLink?: string | null, mapsLabel?: string | null, ticketLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ConcertConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConcertFilter>;
}>;


export type ConcertConnectionQuery = { __typename?: 'Query', concertConnection: { __typename?: 'ConcertConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConcertConnectionEdges', cursor: string, node?: { __typename: 'Concert', id: string, title: string, date: string, locale: string, translationKey: string, program: any, description?: string | null, image?: string | null, helloAssoLink?: string | null, mapsLink?: string | null, mapsLabel?: string | null, ticketLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MusicianQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MusicianQuery = { __typename?: 'Query', musician: { __typename: 'Musician', id: string, name: string, locale: string, translationKey: string, instrument: string, photo: string, photoCredit?: string | null, bio: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MusicianConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MusicianFilter>;
}>;


export type MusicianConnectionQuery = { __typename?: 'Query', musicianConnection: { __typename?: 'MusicianConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MusicianConnectionEdges', cursor: string, node?: { __typename: 'Musician', id: string, name: string, locale: string, translationKey: string, instrument: string, photo: string, photoCredit?: string | null, bio: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FestivalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FestivalQuery = { __typename?: 'Query', festival: { __typename: 'Festival', id: string, title: string, locale: string, translationKey: string, subtitle?: string | null, image?: string | null, imageCaption?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FestivalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FestivalFilter>;
}>;


export type FestivalConnectionQuery = { __typename?: 'Query', festivalConnection: { __typename?: 'FestivalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FestivalConnectionEdges', cursor: string, node?: { __typename: 'Festival', id: string, title: string, locale: string, translationKey: string, subtitle?: string | null, image?: string | null, imageCaption?: string | null, body: any, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, title: string, locale: string, translationKey: string, heroTitle: string, heroSubtitle: string, introTitle?: string | null, introDescription?: string | null, nextConcertCtaLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, title: string, locale: string, translationKey: string, heroTitle: string, heroSubtitle: string, introTitle?: string | null, introDescription?: string | null, nextConcertCtaLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TicketInfoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TicketInfoQuery = { __typename?: 'Query', ticketInfo: { __typename: 'TicketInfo', id: string, title: string, locale: string, translationKey: string, sectionTitle?: string | null, sectionSubtitle?: string | null, discountText?: string | null, email?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cards?: Array<{ __typename: 'TicketInfoCards', title?: string | null, text?: string | null } | null> | null } };

export type TicketInfoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TicketInfoFilter>;
}>;


export type TicketInfoConnectionQuery = { __typename?: 'Query', ticketInfoConnection: { __typename?: 'TicketInfoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TicketInfoConnectionEdges', cursor: string, node?: { __typename: 'TicketInfo', id: string, title: string, locale: string, translationKey: string, sectionTitle?: string | null, sectionSubtitle?: string | null, discountText?: string | null, email?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cards?: Array<{ __typename: 'TicketInfoCards', title?: string | null, text?: string | null } | null> | null } | null } | null> | null } };

export type ContactInfoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactInfoQuery = { __typename?: 'Query', contactInfo: { __typename: 'ContactInfo', id: string, title: string, locale: string, translationKey: string, email?: string | null, address?: string | null, phone?: string | null, mapEmbedUrl?: string | null, facebookUrl?: string | null, instagramUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactInfoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactInfoFilter>;
}>;


export type ContactInfoConnectionQuery = { __typename?: 'Query', contactInfoConnection: { __typename?: 'ContactInfoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactInfoConnectionEdges', cursor: string, node?: { __typename: 'ContactInfo', id: string, title: string, locale: string, translationKey: string, email?: string | null, address?: string | null, phone?: string | null, mapEmbedUrl?: string | null, facebookUrl?: string | null, instagramUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SupportInfoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SupportInfoQuery = { __typename?: 'Query', supportInfo: { __typename: 'SupportInfo', id: string, title: string, locale: string, translationKey: string, subtitle?: string | null, membershipUrl?: string | null, donationUrl?: string | null, membershipTitle?: string | null, membershipText?: string | null, donationTitle?: string | null, donationText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SupportInfoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SupportInfoFilter>;
}>;


export type SupportInfoConnectionQuery = { __typename?: 'Query', supportInfoConnection: { __typename?: 'SupportInfoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SupportInfoConnectionEdges', cursor: string, node?: { __typename: 'SupportInfo', id: string, title: string, locale: string, translationKey: string, subtitle?: string | null, membershipUrl?: string | null, donationUrl?: string | null, membershipTitle?: string | null, membershipText?: string | null, donationTitle?: string | null, donationText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ConcertPartsFragmentDoc = gql`
    fragment ConcertParts on Concert {
  __typename
  title
  date
  locale
  translationKey
  program
  description
  image
  helloAssoLink
  mapsLink
  mapsLabel
  ticketLabel
}
    `;
export const MusicianPartsFragmentDoc = gql`
    fragment MusicianParts on Musician {
  __typename
  name
  locale
  translationKey
  instrument
  photo
  photoCredit
  bio
}
    `;
export const FestivalPartsFragmentDoc = gql`
    fragment FestivalParts on Festival {
  __typename
  title
  locale
  translationKey
  subtitle
  image
  imageCaption
  body
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  title
  locale
  translationKey
  heroTitle
  heroSubtitle
  introTitle
  introDescription
  nextConcertCtaLabel
}
    `;
export const TicketInfoPartsFragmentDoc = gql`
    fragment TicketInfoParts on TicketInfo {
  __typename
  title
  locale
  translationKey
  sectionTitle
  sectionSubtitle
  discountText
  email
  cards {
    __typename
    title
    text
  }
}
    `;
export const ContactInfoPartsFragmentDoc = gql`
    fragment ContactInfoParts on ContactInfo {
  __typename
  title
  locale
  translationKey
  email
  address
  phone
  mapEmbedUrl
  facebookUrl
  instagramUrl
}
    `;
export const SupportInfoPartsFragmentDoc = gql`
    fragment SupportInfoParts on SupportInfo {
  __typename
  title
  locale
  translationKey
  subtitle
  membershipUrl
  donationUrl
  membershipTitle
  membershipText
  donationTitle
  donationText
}
    `;
export const ConcertDocument = gql`
    query concert($relativePath: String!) {
  concert(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConcertParts
  }
}
    ${ConcertPartsFragmentDoc}`;
export const ConcertConnectionDocument = gql`
    query concertConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConcertFilter) {
  concertConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConcertParts
      }
    }
  }
}
    ${ConcertPartsFragmentDoc}`;
export const MusicianDocument = gql`
    query musician($relativePath: String!) {
  musician(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MusicianParts
  }
}
    ${MusicianPartsFragmentDoc}`;
export const MusicianConnectionDocument = gql`
    query musicianConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MusicianFilter) {
  musicianConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MusicianParts
      }
    }
  }
}
    ${MusicianPartsFragmentDoc}`;
export const FestivalDocument = gql`
    query festival($relativePath: String!) {
  festival(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FestivalParts
  }
}
    ${FestivalPartsFragmentDoc}`;
export const FestivalConnectionDocument = gql`
    query festivalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FestivalFilter) {
  festivalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FestivalParts
      }
    }
  }
}
    ${FestivalPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const TicketInfoDocument = gql`
    query ticketInfo($relativePath: String!) {
  ticketInfo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TicketInfoParts
  }
}
    ${TicketInfoPartsFragmentDoc}`;
export const TicketInfoConnectionDocument = gql`
    query ticketInfoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TicketInfoFilter) {
  ticketInfoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TicketInfoParts
      }
    }
  }
}
    ${TicketInfoPartsFragmentDoc}`;
export const ContactInfoDocument = gql`
    query contactInfo($relativePath: String!) {
  contactInfo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactInfoParts
  }
}
    ${ContactInfoPartsFragmentDoc}`;
export const ContactInfoConnectionDocument = gql`
    query contactInfoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactInfoFilter) {
  contactInfoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactInfoParts
      }
    }
  }
}
    ${ContactInfoPartsFragmentDoc}`;
export const SupportInfoDocument = gql`
    query supportInfo($relativePath: String!) {
  supportInfo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SupportInfoParts
  }
}
    ${SupportInfoPartsFragmentDoc}`;
export const SupportInfoConnectionDocument = gql`
    query supportInfoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SupportInfoFilter) {
  supportInfoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SupportInfoParts
      }
    }
  }
}
    ${SupportInfoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      concert(variables: ConcertQueryVariables, options?: C): Promise<{data: ConcertQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConcertQueryVariables, query: string}> {
        return requester<{data: ConcertQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConcertQueryVariables, query: string}, ConcertQueryVariables>(ConcertDocument, variables, options);
      },
    concertConnection(variables?: ConcertConnectionQueryVariables, options?: C): Promise<{data: ConcertConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConcertConnectionQueryVariables, query: string}> {
        return requester<{data: ConcertConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConcertConnectionQueryVariables, query: string}, ConcertConnectionQueryVariables>(ConcertConnectionDocument, variables, options);
      },
    musician(variables: MusicianQueryVariables, options?: C): Promise<{data: MusicianQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MusicianQueryVariables, query: string}> {
        return requester<{data: MusicianQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MusicianQueryVariables, query: string}, MusicianQueryVariables>(MusicianDocument, variables, options);
      },
    musicianConnection(variables?: MusicianConnectionQueryVariables, options?: C): Promise<{data: MusicianConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MusicianConnectionQueryVariables, query: string}> {
        return requester<{data: MusicianConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MusicianConnectionQueryVariables, query: string}, MusicianConnectionQueryVariables>(MusicianConnectionDocument, variables, options);
      },
    festival(variables: FestivalQueryVariables, options?: C): Promise<{data: FestivalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FestivalQueryVariables, query: string}> {
        return requester<{data: FestivalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FestivalQueryVariables, query: string}, FestivalQueryVariables>(FestivalDocument, variables, options);
      },
    festivalConnection(variables?: FestivalConnectionQueryVariables, options?: C): Promise<{data: FestivalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FestivalConnectionQueryVariables, query: string}> {
        return requester<{data: FestivalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FestivalConnectionQueryVariables, query: string}, FestivalConnectionQueryVariables>(FestivalConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    ticketInfo(variables: TicketInfoQueryVariables, options?: C): Promise<{data: TicketInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TicketInfoQueryVariables, query: string}> {
        return requester<{data: TicketInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TicketInfoQueryVariables, query: string}, TicketInfoQueryVariables>(TicketInfoDocument, variables, options);
      },
    ticketInfoConnection(variables?: TicketInfoConnectionQueryVariables, options?: C): Promise<{data: TicketInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TicketInfoConnectionQueryVariables, query: string}> {
        return requester<{data: TicketInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TicketInfoConnectionQueryVariables, query: string}, TicketInfoConnectionQueryVariables>(TicketInfoConnectionDocument, variables, options);
      },
    contactInfo(variables: ContactInfoQueryVariables, options?: C): Promise<{data: ContactInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactInfoQueryVariables, query: string}> {
        return requester<{data: ContactInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactInfoQueryVariables, query: string}, ContactInfoQueryVariables>(ContactInfoDocument, variables, options);
      },
    contactInfoConnection(variables?: ContactInfoConnectionQueryVariables, options?: C): Promise<{data: ContactInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactInfoConnectionQueryVariables, query: string}> {
        return requester<{data: ContactInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactInfoConnectionQueryVariables, query: string}, ContactInfoConnectionQueryVariables>(ContactInfoConnectionDocument, variables, options);
      },
    supportInfo(variables: SupportInfoQueryVariables, options?: C): Promise<{data: SupportInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportInfoQueryVariables, query: string}> {
        return requester<{data: SupportInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportInfoQueryVariables, query: string}, SupportInfoQueryVariables>(SupportInfoDocument, variables, options);
      },
    supportInfoConnection(variables?: SupportInfoConnectionQueryVariables, options?: C): Promise<{data: SupportInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportInfoConnectionQueryVariables, query: string}> {
        return requester<{data: SupportInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportInfoConnectionQueryVariables, query: string}, SupportInfoConnectionQueryVariables>(SupportInfoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/406dd4fa-a226-4261-a62a-82c3f213d9cc/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  